version: '3.8'

# Services
services:
  # Server service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:3001"
    env_file: ./.env
    environment:
      - DB_HOST=mongodb_server
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
      - MONGODB_URI=$MONGODB_URI
    depends_on:
      - mongodb

  # Client service
  client:
    build:
      context: ./client
      dockerfile: Dockerfile

    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - server

  # Database service
  mongodb:
    image: mongo:latest
    container_name: mongodb_server

    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
      - MONGO_INITDB_DATABASE=$MONGODB_DATABASE

    ports:
      - "27017:27017"

    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

# Volumes
volumes: 
  mongodata: